export interface Language {
  code?: string;
  name: string;
  flag: string;
  image?: string;
  translateCode?: string;
}

export const ALL_LANGUAGES: Language[] = [
  {
    code: 'auto',
    name: "I don't know",
    flag: '🤖',
    translateCode: '',
  },
  {
    code: 'af',
    name: 'Afrikaans',
    flag: '🇿🇦',
    image: 'af.webp',
    translateCode: 'af',
  },
  {
    code: 'sq',
    name: 'Albanian',
    flag: '🇦🇱',
    image: 'sq.webp',
    translateCode: 'sq',
  },
  {
    code: 'am',
    name: 'Amharic',
    flag: '🇪🇹',
    image: 'am.webp',
    translateCode: 'am',
  },
  {
    code: 'ar',
    name: 'Arabic',
    flag: '🇸🇦',
    image: 'ar.webp',
    translateCode: 'ar',
  },
  {
    code: 'hy',
    name: 'Armenian',
    flag: '🇦🇲',
    image: 'hy.webp',
    translateCode: 'hy',
  },
  {
    code: 'as',
    name: 'Assamese',
    flag: '🇮🇳',
    image: '',
    translateCode: '',
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    flag: '🇦🇿',
    image: 'az.webp',
    translateCode: 'az',
  },
  {
    code: 'ba',
    name: 'Bashkir',
    flag: '🇷🇺',
    image: 'ru.webp',
    translateCode: '',
  },
  {
    code: 'eu',
    name: 'Basque',
    flag: '🇪🇸',
    image: 'eu.webp',
    translateCode: 'eu',
  },
  {
    code: 'be',
    name: 'Belarusian',
    flag: '🇧🇾',
    image: 'be.webp',
    translateCode: 'be',
  },
  {
    code: 'bn',
    name: 'Bengali',
    flag: '🇧🇩',
    image: 'bn.webp',
    translateCode: 'bn',
  },
  {
    code: 'bs',
    name: 'Bosnian',
    flag: '🇧🇦',
    image: 'bs.webp',
    translateCode: 'bs',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    flag: '🇧🇬',
    image: 'bg.webp',
    translateCode: 'bg',
  },
  {
    code: 'my',
    name: 'Burmese',
    flag: '🇲🇲',
    image: 'my.webp',
    translateCode: 'my',
  },
  {
    code: 'ca',
    name: 'Catalan',
    flag: '🇪🇸',
    image: 'ca.webp',
    translateCode: 'ca',
  },
  {
    code: '',
    name: 'Cebuano',
    flag: '🇵🇭',
    image: '',
    translateCode: 'ceb',
  },
  {
    code: 'zh',
    name: 'Chinese',
    flag: '🇨🇳',
    image: 'zh.webp',
    translateCode: 'zh-CN',
  },
  {
    code: '',
    name: 'Chinese (Simplified)',
    flag: '🇨🇳',
    image: 'zh.webp',
    translateCode: 'zh-CN',
  },
  {
    code: '',
    name: 'Chinese (Traditional)',
    flag: '🇹🇼',
    image: 'zh.webp',
    translateCode: 'zh-TW',
  },
  {
    code: '',
    name: 'Corsican',
    flag: '🇫🇷',
    image: 'co.webp',
    translateCode: 'co',
  },
  {
    code: 'hr',
    name: 'Croatian',
    flag: '🇭🇷',
    image: 'hr.webp',
    translateCode: 'hr',
  },
  {
    code: 'cs',
    name: 'Czech',
    flag: '🇨🇿',
    image: 'cs.webp',
    translateCode: 'cs',
  },
  {
    code: 'da',
    name: 'Danish',
    flag: '🇩🇰',
    image: 'da.webp',
    translateCode: 'da',
  },
  {
    code: 'nl',
    name: 'Dutch',
    flag: '🇳🇱',
    image: 'nl.webp',
    translateCode: 'nl',
  },
  {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    image: 'en.webp',
    translateCode: 'en',
  },
  {
    code: '',
    name: 'Esperanto',
    flag: '🌍',
    image: 'eo.webp',
    translateCode: 'eo',
  },
  {
    code: 'et',
    name: 'Estonian',
    flag: '🇪🇪',
    image: 'et.webp',
    translateCode: 'et',
  },
  {
    code: 'tl',
    name: 'Tagalog',
    flag: '🇵🇭',
    image: 'tl.webp',
    translateCode: 'tl',
  },
  {
    code: 'fi',
    name: 'Finnish',
    flag: '🇫🇮',
    image: 'fi.webp',
    translateCode: 'fi',
  },
  {
    code: 'fr',
    name: 'French',
    flag: '🇫🇷',
    image: 'fr.webp',
    translateCode: 'fr',
  },
  {
    code: '',
    name: 'Frisian',
    flag: '🇳🇱',
    image: 'fy.webp',
    translateCode: 'fy',
  },
  {
    code: 'gl',
    name: 'Galician',
    flag: '🇪🇸',
    image: 'gl.webp',
    translateCode: 'gl',
  },
  {
    code: 'ka',
    name: 'Georgian',
    flag: '🇬🇪',
    image: 'ka.webp',
    translateCode: 'ka',
  },
  {
    code: 'de',
    name: 'German',
    flag: '🇩🇪',
    image: 'de.webp',
    translateCode: 'de',
  },
  {
    code: 'el',
    name: 'Greek',
    flag: '🇬🇷',
    image: 'el.webp',
    translateCode: 'el',
  },
  {
    code: 'gu',
    name: 'Gujarati',
    flag: '🇮🇳',
    image: 'gu.webp',
    translateCode: 'gu',
  },
  {
    code: 'ht',
    name: 'Haitian Creole',
    flag: '🇭🇹',
    image: 'ht.webp',
    translateCode: 'ht',
  },
  {
    code: '',
    name: 'Hausa',
    flag: '🇳🇬',
    image: 'ha.webp',
    translateCode: 'ha',
  },
  {
    code: 'haw',
    name: 'Hawaiian',
    flag: '🇺🇸',
    image: 'haw.webp',
    translateCode: '',
  },
  {
    code: 'he',
    name: 'Hebrew',
    flag: '🇮🇱',
    image: 'he.webp',
    translateCode: 'iw',
  },
  {
    code: 'hi',
    name: 'Hindi',
    flag: '🇮🇳',
    image: 'hi.webp',
    translateCode: 'hi',
  },
  {
    code: '',
    name: 'Hmong',
    flag: '🇱🇦',
    image: 'hmn.webp',
    translateCode: 'hmn',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    flag: '🇭🇺',
    image: 'hu.webp',
    translateCode: 'hu',
  },
  {
    code: 'is',
    name: 'Icelandic',
    flag: '🇮🇸',
    image: 'is.webp',
    translateCode: 'is',
  },
  { code: '', name: 'Igbo', flag: '🇳🇬', image: 'ig.webp', translateCode: 'ig' },
  {
    code: 'id',
    name: 'Indonesian',
    flag: '🇮🇩',
    image: 'id.webp',
    translateCode: 'id',
  },
  {
    code: 'ga',
    name: 'Irish',
    flag: '🇮🇪',
    image: 'ga.webp',
    translateCode: 'ga',
  },
  {
    code: 'it',
    name: 'Italian',
    flag: '🇮🇹',
    image: 'it.webp',
    translateCode: 'it',
  },
  {
    code: 'ja',
    name: 'Japanese',
    flag: '🇯🇵',
    image: 'ja.webp',
    translateCode: 'ja',
  },
  {
    code: 'jw',
    name: 'Javanese',
    flag: '🇮🇩',
    image: 'jw.webp',
    translateCode: 'jv',
  },
  {
    code: 'kn',
    name: 'Kannada',
    flag: '🇮🇳',
    image: 'kn.webp',
    translateCode: 'kn',
  },
  {
    code: 'kk',
    name: 'Kazakh',
    flag: '🇰🇿',
    image: 'kk.webp',
    translateCode: 'kk',
  },
  {
    code: 'km',
    name: 'Khmer',
    flag: '🇰🇭',
    image: 'km.webp',
    translateCode: 'km',
  },
  {
    code: 'ko',
    name: 'Korean',
    flag: '🇰🇷',
    image: 'ko.webp',
    translateCode: 'ko',
  },
  {
    code: '',
    name: 'Kurdish (Kurmanji)',
    flag: '🇹🇷',
    image: 'ku.webp',
    translateCode: 'ku',
  },
  {
    code: '',
    name: 'Kyrgyz',
    flag: '🇰🇬',
    image: 'ky.webp',
    translateCode: 'ky',
  },
  {
    code: 'lo',
    name: 'Lao',
    flag: '🇱🇦',
    image: 'lo.webp',
    translateCode: 'lo',
  },
  {
    code: 'la',
    name: 'Latin',
    flag: '🇻🇦',
    image: 'la.webp',
    translateCode: '',
  },
  {
    code: 'lv',
    name: 'Latvian',
    flag: '🇱🇻',
    image: 'lv.webp',
    translateCode: 'lv',
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    flag: '🇱🇹',
    image: 'lt.webp',
    translateCode: 'lt',
  },
  {
    code: 'lb',
    name: 'Luxembourgish',
    flag: '🇱🇺',
    image: 'lb.webp',
    translateCode: '',
  },
  {
    code: 'mk',
    name: 'Macedonian',
    flag: '🇲🇰',
    image: 'mk.webp',
    translateCode: 'mk',
  },
  {
    code: 'mg',
    name: 'Malagasy',
    flag: '🇲🇬',
    image: 'mg.webp',
    translateCode: 'mg',
  },
  {
    code: 'ms',
    name: 'Malay',
    flag: '🇲🇾',
    image: 'ms.webp',
    translateCode: 'ms',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    flag: '🇮🇳',
    image: 'ml.webp',
    translateCode: 'ml',
  },
  {
    code: 'mt',
    name: 'Maltese',
    flag: '🇲🇹',
    image: 'mt.webp',
    translateCode: 'mt',
  },
  {
    code: 'mi',
    name: 'Maori',
    flag: '🇳🇿',
    image: 'mi.webp',
    translateCode: '',
  },
  {
    code: 'mr',
    name: 'Marathi',
    flag: '🇮🇳',
    image: 'mr.webp',
    translateCode: 'mr',
  },
  {
    code: 'mn',
    name: 'Mongolian',
    flag: '🇲🇳',
    image: 'mn.webp',
    translateCode: 'mn',
  },
  {
    code: 'ne',
    name: 'Nepali',
    flag: '🇳🇵',
    image: 'ne.webp',
    translateCode: 'ne',
  },
  {
    code: 'no',
    name: 'Norwegian',
    flag: '🇳🇴',
    image: 'no.webp',
    translateCode: 'no',
  },
  {
    code: 'nn',
    name: 'Norwegian Nynorsk',
    flag: '🇳🇴',
    image: 'no.webp',
    translateCode: '',
  },
  {
    code: 'oc',
    name: 'Occitan',
    flag: '🇫🇷',
    image: '',
    translateCode: '',
  },
  {
    code: 'ps',
    name: 'Pashto',
    flag: '🇦🇫',
    image: 'ps.webp',
    translateCode: 'ps',
  },
  {
    code: 'fa',
    name: 'Persian',
    flag: '🇮🇷',
    image: 'fa.webp',
    translateCode: 'fa',
  },
  {
    code: 'pl',
    name: 'Polish',
    flag: '🇵🇱',
    image: 'pl.webp',
    translateCode: 'pl',
  },
  {
    code: 'pt',
    name: 'Portuguese',
    flag: '🇵🇹',
    image: 'pt.webp',
    translateCode: 'pt',
  },
  {
    code: 'pa',
    name: 'Punjabi',
    flag: '🇮🇳',
    image: 'pa.webp',
    translateCode: 'pa',
  },
  {
    code: 'ro',
    name: 'Romanian',
    flag: '🇷🇴',
    image: 'ro.webp',
    translateCode: 'ro',
  },
  {
    code: 'ru',
    name: 'Russian',
    flag: '🇷🇺',
    image: 'ru.webp',
    translateCode: 'ru',
  },
  {
    code: 'sm',
    name: 'Samoan',
    flag: '🇼🇸',
    image: 'sm.webp',
    translateCode: 'sm',
  },
  {
    code: 'gd',
    name: 'Scots Gaelic',
    flag: '🏴',
    image: 'gd.webp',
    translateCode: 'gd',
  },
  {
    code: 'sr',
    name: 'Serbian',
    flag: '🇷🇸',
    image: 'sr.webp',
    translateCode: 'sr',
  },
  {
    code: 'st',
    name: 'Sesotho',
    flag: '🇱🇸',
    image: 'st.webp',
    translateCode: 'st',
  },
  {
    code: 'sn',
    name: 'Shona',
    flag: '🇿🇼',
    image: 'sn.webp',
    translateCode: '',
  },
  {
    code: 'sd',
    name: 'Sindhi',
    flag: '🇵🇰',
    image: 'sd.webp',
    translateCode: 'sd',
  },
  {
    code: 'si',
    name: 'Sinhala',
    flag: '🇱🇰',
    image: 'si.webp',
    translateCode: 'si',
  },
  {
    code: 'sk',
    name: 'Slovak',
    flag: '🇸🇰',
    image: 'sk.webp',
    translateCode: 'sk',
  },
  {
    code: 'sl',
    name: 'Slovenian',
    flag: '🇸🇮',
    image: 'sl.webp',
    translateCode: 'sl',
  },
  {
    code: 'so',
    name: 'Somali',
    flag: '🇸🇴',
    image: 'so.webp',
    translateCode: 'so',
  },
  {
    code: 'es',
    name: 'Spanish',
    flag: '🇪🇸',
    image: 'es.webp',
    translateCode: 'es',
  },
  {
    code: 'su',
    name: 'Sundanese',
    flag: '🇮🇩',
    image: 'su.webp',
    translateCode: 'su',
  },
  {
    code: 'sw',
    name: 'Swahili',
    flag: '🇰🇪',
    image: 'sw.webp',
    translateCode: 'sw',
  },
  {
    code: 'sv',
    name: 'Swedish',
    flag: '🇸🇪',
    image: 'sv.webp',
    translateCode: 'sv',
  },
  {
    code: 'tg',
    name: 'Tajik',
    flag: '🇹🇯',
    image: 'tg.webp',
    translateCode: '',
  },
  {
    code: 'ta',
    name: 'Tamil',
    flag: '🇮🇳',
    image: 'ta.webp',
    translateCode: 'ta',
  },
  {
    code: 'tt',
    name: 'Tatar',
    flag: '🇷🇺',
    image: '',
    translateCode: '',
  },
  {
    code: 'te',
    name: 'Telugu',
    flag: '🇮🇳',
    image: 'te.webp',
    translateCode: 'te',
  },
  {
    code: 'th',
    name: 'Thai',
    flag: '🇹🇭',
    image: 'th.webp',
    translateCode: 'th',
  },
  {
    code: 'tr',
    name: 'Turkish',
    flag: '🇹🇷',
    image: 'tr.webp',
    translateCode: 'tr',
  },
  {
    code: 'tk',
    name: 'Turkmen',
    flag: '🇹🇲',
    image: '',
    translateCode: '',
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    flag: '🇺🇦',
    image: 'uk.webp',
    translateCode: 'uk',
  },
  {
    code: 'ur',
    name: 'Urdu',
    flag: '🇵🇰',
    image: 'ur.webp',
    translateCode: 'ur',
  },
  {
    code: '',
    name: 'Uyghur',
    flag: '🇨🇳',
    image: 'ug.webp',
    translateCode: 'ug',
  },
  {
    code: 'uz',
    name: 'Uzbek',
    flag: '🇺🇿',
    image: 'uz.webp',
    translateCode: 'uz',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    flag: '🇻🇳',
    image: 'vi.webp',
    translateCode: 'vi',
  },
  {
    code: 'cy',
    name: 'Welsh',
    flag: '🏴',
    image: 'cy.webp',
    translateCode: 'cy',
  },
  {
    code: '',
    name: 'Xhosa',
    flag: '🇿🇦',
    image: 'xh.webp',
    translateCode: 'xh',
  },
  {
    code: 'yi',
    name: 'Yiddish',
    flag: '🇮🇱',
    image: 'yi.webp',
    translateCode: '',
  },
  {
    code: 'yo',
    name: 'Yoruba',
    flag: '🇳🇬',
    image: 'yo.webp',
    translateCode: 'yo',
  },
  { code: '', name: 'Zulu', flag: '🇿🇦', image: 'zu.webp', translateCode: 'zu' },
  {
    code: 'ceb',
    name: 'Cebuano',
    flag: '🇵🇭',
    image: '',
    translateCode: 'ceb',
  },
  {
    code: 'co',
    name: 'Corsican',
    flag: '🇫🇷',
    image: '',
    translateCode: 'co',
  },
  {
    code: 'eo',
    name: 'Esperanto',
    flag: '🌍',
    image: '',
    translateCode: 'eo',
  },
  {
    code: 'fy',
    name: 'Frisian',
    flag: '🇳🇱',
    image: '',
    translateCode: 'fy',
  },
  {
    code: 'gd',
    name: 'Scots Gaelic',
    flag: '🏴',
    image: '',
    translateCode: 'gd',
  },
  {
    code: 'hmn',
    name: 'Hmong',
    flag: '🇱🇦',
    image: '',
    translateCode: 'hmn',
  },
  {
    code: 'ig',
    name: 'Igbo',
    flag: '🇳🇬',
    image: '',
    translateCode: 'ig',
  },
  {
    code: 'ku',
    name: 'Kurdish (Kurmanji)',
    flag: '🇹🇷',
    image: '',
    translateCode: 'ku',
  },
  {
    code: 'ky',
    name: 'Kyrgyz',
    flag: '🇰🇬',
    image: '',
    translateCode: 'ky',
  },
  {
    code: 'sm',
    name: 'Samoan',
    flag: '🇼🇸',
    image: '',
    translateCode: 'sm',
  },
  {
    code: 'st',
    name: 'Sesotho',
    flag: '🇱🇸',
    image: '',
    translateCode: 'st',
  },
];

export const DEFAULT_SUGGESTIONS = ['auto', 'he', 'en', 'ar', 'es', 'fr'];

export const findLanguage = (code: string): Language | undefined => {
  return ALL_LANGUAGES.find((lang) => lang.code === code);
};

// Find language by either ISO code or provider translateCode
export const findLanguageByAnyCode = (code: string): Language | undefined => {
  return ALL_LANGUAGES.find(
    (lang) => lang.code === code || lang.translateCode === code
  );
};

export const getLastUsedLanguage = (): string => {
  if (typeof window === 'undefined') return 'auto';
  return localStorage.getItem('vidto.lastLanguage') || 'auto';
};

export const setLastUsedLanguage = (code: string): void => {
  if (typeof window !== 'undefined') {
    localStorage.setItem('vidto.lastLanguage', code);
  }
};
